import type { Metadata } from "next";
import "./globals.css";
import { AuthContextProvider } from "@/context/auth.context";
import { Toaster } from "react-hot-toast";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
                position="top-center"
                reverseOrder={false}
            />
        <AuthContextProvider>
          {children}
        </ AuthContextProvider>
      </body>
    </html>


  );
}
//  RootLayout.propTypes = {
//     children: PropTypes.node.isRequired,
//   }